# Generated by Django 3.1.4 on 2021-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_auto_20210305_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
